---
title: "Introduction"
author: "Colin Rundel"
date: "2017-01-09"
output:
  xaringan::moon_reader:
    css: "slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

exclude: true

```{r, message=FALSE, warning=FALSE, include=FALSE}
options(
  htmltools.dir.version = FALSE # for blogdown
)

library(emo)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

---

## Policies

* Plagiarism
    + Use online resources but make sure to cite them
    + No direct code sharing between groups / individuals
* Homework
    + Group based, everyone is equally responsible
* Late work
    + late, but same day: -10%
    + late, next day:  -20%
    + 2 days or later: no credit
* Exams
    + 2 Midterms, take home

---

## Grading

<br/>

.center[

Component     |  Percentage
:-------------|--------------
Homework      |  50%
Midterm 1     |  20%
Midterm 2     |  20%
Final Project |  10%

]

---

## Groups

* Group homework assignments
    + Roughly biweekly assignments
    + Open ended
    + 10 - 20 hours of work each
    + Peer review at the end

<br/>

* Expectations and roles
    + Everyone is expected to contribute equally
    + Everyone is expected to understand *all* code turned in
    + Individual contribution evaluated by peer assessment

---

## Reproducible Research / Computing

* Unix shell

* R + RStudio

* rmarkdown + make

* Git + github

---

## Academic integrity

> To uphold the Duke Community Standard:

> - I will not lie, cheat, or steal in my academic endeavors;
> - I will conduct myself honorably in all my endeavors; and
> - I will act if the Standard is compromised.

---

## Collaboration policy


- Only work that is clearly assigned as team work should be completed collaboratively (Homework). 

- On take home exams you may not directly share or discuss code with anyone other than the Professor and TAs

- On homeworks you may not directly share code with other team(s) in this class, however you are welcome to discuss the problems together and ask for advice


---

## Sharing / reusing code policy

- I am well aware that a huge volume of code is available on the web to solve any number of problems.

- Unless I explicitly tell you not to use something the course's policy is that you may make use of any online resources (e.g. Google, StackOverflow, etc.) but you must explicitly cite where you obtained any code you directly use (or use as inspiration). 

- Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. 



---

## Before next Tuesday

* Create a github account if you don't have one

* Complete the course survey (link via email)

* Install recommended [software](https://stat.duke.edu/~cr173/Sta323_Sp18#software)

* Once I let you know (via email) try to login in to [gort](https://gort.stat.duke.edu:8787)
